jasa/jasa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')), 

    path('', include('telegram.urls')),
    path('', include('events.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

jasa/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)

from . import views


app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(
            template_name='users/signup.html',
        ),
        name='signup'
    ),
    path(
        'login/',
        views.UpdatedLoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logout.html'
        ),
        name='logout'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
] 

jasa/users/models.py
from django.db import models

# Create your models here.

jasa/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email')


class LoginForm(AuthenticationForm):
    """Custom LoginForm to add a 'remember me' checkbox"""

    username = forms.CharField(
        label='',
        max_length=30,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Username'}
        )
    )
    password = forms.CharField(
        label='',
        max_length=30,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Password'},
            render_value=True
        )
    )
    remember_me = forms.BooleanField(
        label='Remember me',
        required=False,
        initial=False,
        widget=forms.CheckboxInput()
    )

jasa/users/views.py
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView

from django.urls import reverse_lazy

from .forms import CreationForm, LoginForm


class SignUp(CreateView):
    """This view is used to create a new user."""

    form_class = CreationForm
    success_url = reverse_lazy('events:index')


# https://stackoverflow.com/questions/53431476/django-how-to-implement-a-remember-me-radio-button-on-a-login-page
class UpdatedLoginView(LoginView):
    """This view implments some more features on LoginView"""

    form_class = LoginForm

    def get_initial(self):
        auth_data = self.request.session.get('remember_me', {})

        self.initial['username'] = auth_data.get('username', '')
        self.initial['password'] = auth_data.get('password', '')
        self.initial['remember_me'] = False

        return super(UpdatedLoginView, self).get_initial()

    def get_context_data(self, **kwargs):
        context = super(UpdatedLoginView, self).get_context_data(**kwargs)
        return context


    def form_valid(self, form):
        username = form.cleaned_data['username'].strip()
        password = form.cleaned_data['password'].strip()
        remember_me = form.cleaned_data['remember_me']

        current_session = self.request.session

        if remember_me:
            print(username, password, remember_me)
            current_session['remember_me'] = {
                'username': username,
                'password': password
            }
            current_session.set_expiry(1209600) # 2 weeks
            current_session.modified = True
    
        return super(UpdatedLoginView, self).form_valid(form)

jasa/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card tg-bg-color border-0">
        <div class="card-body">    
          <img 
            class="mx-auto d-block my-3" 
            src="{% static 'img/jasa-logo-final.png' %}" alt="Jasa Logo" width="20%"
          />
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form 
            class="p-4"
            method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
            >
              {% csrf_token %}

              {% for field in form %}
                <div class="form-group mb-4">

                  {{ field }}

                  {% if field.label %}
                    <label for="{{ field.id_for_label }}" class="form-label">
                      {{ field.label }}
                    </label>
                  {% endif %}

                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}

              <button type="submit" class="btn outline-btn w-100">
                Login
              </button>
            </form>
          </div>
        </div>
        <div class="text-center">
          <a href="{% url 'users:password_reset' %}" class="ml-auto">
            <small>Forgot password?</small>
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

jasa/templates/users/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock %}

{% block header_title %}Logged out{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Logout</h1>
            <p>You are now logged out.</p>
            <a href="{% url 'users:login' %}">Login again</a>
        </div>
    </div>
  </div>
{% endblock %}

jasa/templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %}Password Reset Form{% endblock %}


{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          To reset the old password, enter the email address under which you registered.
        </div>
        <div class="card-body"> 
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %} 

            <div class="form-group row my-3 p-3">
              <label for="id_email">
                Email address
                <span class="required text-danger">*</span>
              </label>    
              <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
            </div>

            <button type="submit" class="btn outline-btn w-100">
              Reset Password
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

jasa/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Password reset was successful{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Password recovery completed
        </div>
        <div class="card-body">
          <p>Your password has been saved. Use it to log in</p>
          <a href="{% url 'users:login' %}">войти</a>
        </div> 
      </div> 
    </div>
  </div> 
{% endblock %}

jasa/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}New Password{% endblock %}

{% block content %}
{% load user_filters %}
  {% if validlink %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Enter a new password
          </div>
          <div class="card-body">
            {% load user_filters %}
            {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
            {% endif %}
            
            <form 
              method="post"
              {% if form_action_url %}
                action="{% url form_action_url %}"
              {% endif %}
            >
              {% csrf_token %}
            
              {% for field in form %}
                <div class="form-group col my-3"
                  {% if field.field.required %} 
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}
                >
                  <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
            
                  <div>
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
              
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Submit
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Error
          </div>
          <div class="card-body">
            <p>The password reset link contains an error or is outdated.</p>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

jasa/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Password reset was successful{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          An email has been sent
        </div>
        <div class="card-body">
          <p>Check your email, you should receive an email with a link to restore your password</p>
        </div> 
      </div> 
    </div>
  </div> 
{% endblock %}

jasa/templates/users/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Signup{% endblock %}

{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card tg-bg-color border-0">
        <div class="card-body p-0">    
          <img 
            class="mx-auto d-block my-3" 
            src="{% static 'img/jasa-logo-final.png' %}" alt="Jasa Logo" width="20%"
          />
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form 
            class="p-4"
            method="post"
            action="{% url 'users:signup' %}"
          >
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group mb-4">
                  {{ field|placeholder:field.label|addclass:'form-control'}}

                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}

              <button type="submit" class="btn outline-btn w-100">
                Register
              </button>
            </form>
          </div>
        </div>
      </div>
    
      <span class="text-muted">
        <small>
          Already have an account? 
          <a href="{% url 'users:login' %}">Login</a>
        </small>
      </span>
    </div>
  </div>
{% endblock %}