jasa/events/urls.py
from django.urls import path

from . import views


app_name = 'events'

urlpatterns = [
    path(
        'events/',
        views.index,
        name='index'
    ),
    path(
        'events/<int:event_id>/',
        views.event_details,
        name='event_details'
    ),
    path(
        'events/like/',
        views.like_event,
        name='like_event'
    ),
    path(
        'events/bookmark/',
        views.bookmark_event,
        name='bookmark_event'
    ),
    path(
        'profile/',
        views.profile,
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'search/',
        views.search,
        name='search'
    )
]

jasa/jasa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')), 

    path('', include('telegram.urls')),
    path('', include('events.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

jasa/events/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Event(models.Model):
    """Event model that saves necessary information about the event."""

    organizer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='events',
        verbose_name='Event organizer',
    )
    title = models.CharField(
        'Event title',
        max_length=255
    )
    short_description = models.CharField(
        'Event short description',
        max_length=255,
        blank=True
    )
    long_description = models.TextField(
        'Event detailed description',
        blank=True
    )
    sign_up_url = models.URLField(
        'Sign up URL'
    )
    photo = models.ImageField(
        'Event photo',
        upload_to='events/',
        blank=True,
    )
    liked = models.ManyToManyField(
        User, 
        related_name='liked_events',
        default=None,
        blank=True,
        verbose_name="likes"
    )
    bookmarked = models.ManyToManyField(
        User,
        related_name='bookmarked_events',
        default=None,
        blank=True,
        verbose_name="bookmarks"
    )
    tags = models.ManyToManyField(
        'Tag',
        related_name='tag_events',
        default=None,
        blank=True,
        verbose_name="tags"
    )

    pub_date = models.DateTimeField(
        'Event publish date',
        auto_now_add=True,
    )

    start_date = models.DateTimeField(
        'Event start date',
        auto_now_add=True,
    )
    end_date = models.DateTimeField(
        'Event end date',
        auto_now_add=True,
    )

    address = models.CharField(
        'Address',
        max_length=255,
        blank=True,
    )
    longitude = models.FloatField(
        'Longitude',
        null=True,
        blank=True,
    )
    latitude = models.FloatField(
        'Latitude',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Event'
        verbose_name_plural = 'Events'
        ordering = ['-pub_date']

    @property
    def num_likes(self):
        return self.liked.count()
    
    @property
    def num_bookmarks(self):
        return self.bookmarked.count()


LIKE_CHOICES = (
    ('like', 'like'),
    ('dislike', 'dislike'),
)


class Like(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
    )
    value = models.CharField(
        choices=LIKE_CHOICES,
        default='like',
        max_length=10,
    )


class Bookmark(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
    )


class Tag(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True,
    )
    events = models.ManyToManyField(
        Event,
        related_name='tag',
        blank=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

jasa/events/views.py
from typing import Optional

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required 
from django.contrib.auth import get_user_model

from core.decorators.ajax_decorator import ajax_login_required
from .constants import NUM_LOAD_EVENTS
from .models import Event, Tag


User = get_user_model()


def paginator_events(request, event_list, num_of_events_per_page):
    """Paginator events."""
    page_number = request.GET.get('page')
    paginator = Paginator(event_list, num_of_events_per_page)

    return paginator.get_page(page_number)


def index(request):
    """Render NUM_LOAD_EVENTS most recent events."""
    template_name = 'events/index.html'
    event_list = Event.objects.all()
    page_obj = paginator_events(request, event_list, NUM_LOAD_EVENTS)

    context = {
        'page_obj': page_obj,
        'show_full': False,
    }
    
    return render(request, template_name, context)


def event_details(request, event_id: int):
    """Render event details."""
    template_name = 'events/event_details.html'
    event = Event.objects.get(id=event_id)

    context = {
        'event': event,
        'show_full': True,
    }

    return render(request, template_name, context)


def profile(request, username: str):
    """Render profile page."""
    template_name = 'events/profile.html'

    username = username or request.user.username
    if not username:
        return redirect('users:login')

    user = get_object_or_404(User, username=username)
    event_list = user.events.all()
    page_obj = paginator_events(request, event_list, NUM_LOAD_EVENTS)

    context = {
        'profile': user,
        'page_obj': page_obj,
    }

    return render(request, template_name, context)


def search(request):
    """Render search page."""
    template_name = 'events/search.html'

    tags = Tag.objects.all()

    context = {
        'tags': tags,
    }

    return render(request, template_name, context)


@ajax_login_required
def like_event(request):
    user = request.user

    try:
        if request.method == 'POST':
            event_id = request.POST.get('event-id')
            event = Event.objects.get(id=event_id)
            
            if user in event.liked.all():
                event.liked.remove(user)
            else:
                event.liked.add(user)

            return JsonResponse({
                'status': 'OK',
                'count': event.num_likes,
                'event-id': event_id,
            })
    except Exception as e:
        print(e)
        return JsonResponse({
            'status': 'ERROR',
        })


@ajax_login_required
def bookmark_event(request):
    user = request.user

    try:
        if request.method == 'POST':
            event_id = request.POST.get('event-id')
            event = Event.objects.get(id=event_id)
            
            if user in event.bookmarked.all():
                event.bookmarked.remove(user)
            else:
                event.bookmarked.add(user)

            return JsonResponse({
                'status': 'OK',
                'count': event.num_bookmarks,
                'event-id': event_id,
            })
    except Exception as e:
        print(e)
        return JsonResponse({
            'status': 'ERROR',
        })

jasa/templates/events/includes/event.html
<article id="event-{{ event.id }}" class="card border-0 rounded tg-bg-color mb-5">
  <div class="row">
    <div class="col-md-6">
      {% comment %} 
      TODO: Display the events organizer.

      Show the organizers profile picture and name. 
      {% endcomment %}
      <div class="profile_header p-2">
        <a href="{% url 'events:profile' event.organizer.username %}">
          {{event.organizer.username}}
        </a>
      </div>
  
      {% comment %} 
      TODO:
      - [ ] Multiple images for the event

      https://getbootstrap.com/docs/4.3/components/carousel/
      {% endcomment %}
      <img 
        class="w-100"
        src="
        {% if event.photo %}
          {{ event.photo.url }}
        {% endif %}
        "
        alt="{{ event.title }}"
      >
      <div class="header px-2">
        {% csrf_token %}
        <ul class="d-flex p-0 m-0 list-unstyled">
          <li class="pr-2">
            <button id="like-button" class="btn p-0" event-id="{{ event.id }}">
              {% if user not in event.liked.all %}
                  <i class="fa-regular fa-heart fa-lg tg-text-color"></i>
              {% else %}
                  <i class="_selected fa-solid fa-heart fa-lg text-danger pulse"></i>
              {% endif %}
            </button>
          </li>
          <li class="px-2">
            <a 
              class="tg-text-color"
              href="https://t.me/share/url?url={{ DOMAIN }}{% url 'events:event_details' event.id %}"
            >
              <i class="fa-regular fa-paper-plane fa-lg"></i>
            </a>
          </li>
          <li class="pl-2 ml-auto">
            <button id="bookmark-button" class="btn p-0" event-id="{{ event.id }}">
              {% if user not in event.bookmarked.all %}
                  <i class="fa-regular fa-bookmark fa-lg tg-text-color"></i>
              {% else %}
                  <i class="_selected fa-solid fa-bookmark fa-lg text-warning"></i>
              {% endif %}
            </button>
          </li>
        </ul>
        <label 
          for="like-button" 
          id="like-counter"
          data-count="{{event.liked.all.count}}"
        >
          {{ event.liked.all.count }} likes
        </label>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card-body p-2">
        <h5 class="card-title">{{ event.title }}</h5>
  
        <p class="card-text">
          {% if show_full %}
            {{ event.long_description|safe}}
          {% else %}
            {{ event.short_description|safe}}
            <a
              class="tg-link-color" 
              href="{% url 'events:event_details' event.id %}"
            >
              Подробнее
            </a>
        {% endif %}
        </p>
  
        <ul class="p-0 list-unstyled">
          <li class="p-0">
            <small class="card-text tg-hint-color text-muted">
              <i class="fa-regular fa-calendar-alt"></i> {{ event.start_date }}
            </small>
          </li>
          {% comment %} 
          TODO: Link to google maps for the event
          {% endcomment %}
          <li class="p-0">
            <small class="card-text tg-hint-color text-muted">
              <i class="fa-regular fa-map"></i> {{ event.address }}
            </small>
          </li>
        </ul>
  
        {% comment %} 
          TODO: Figure out if the user actually signed in or not.
  
          (Perhaps th user gets redirected to register confirmation
          page after signing up to the event.)
  
          If the user is anonymous, redirect them to open the bot, 
          after which they will be redirected to the event details page.
        {% endcomment %}
        <a href="{{ event.sign_up_url }}" target="_blank" class="ml-auto">
          <button class="btn w-100 outline-btn">
            Зарегистрируйтесь сейчас
          </button>
        </a>
      </div>
    </div>
  </div>
</article>