jasa/events/urls.py
from django.urls import path

from . import views


app_name = 'events'

urlpatterns = [
    path(
        'events/',
        views.index,
        name='index'
    ),
    path(
        'events/<int:event_id>/',
        views.event_details,
        name='event_details'
    ),
    path(
        'events/like/',
        views.like_event,
        name='like_event'
    ),
    path(
        'events/bookmark/',
        views.bookmark_event,
        name='bookmark_event'
    ),
    path(
        'profile/',
        views.profile,
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'search/',
        views.search,
        name='search'
    )
]

jasa/jasa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')), 

    path('', include('telegram.urls')),
    path('', include('events.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

jasa/events/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Event(models.Model):
    """Event model that saves necessary information about the event."""

    organizer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='events',
        verbose_name='Event organizer',
    )
    title = models.CharField(
        'Event title',
        max_length=255
    )
    short_description = models.CharField(
        'Event short description',
        max_length=255,
        blank=True
    )
    long_description = models.TextField(
        'Event detailed description',
        blank=True
    )
    sign_up_url = models.URLField(
        'Sign up URL'
    )
    photo = models.ImageField(
        'Event photo',
        upload_to='events/',
        blank=True,
    )
    liked = models.ManyToManyField(
        User, 
        related_name='liked_events',
        default=None,
        blank=True,
        verbose_name="likes"
    )
    bookmarked = models.ManyToManyField(
        User,
        related_name='bookmarked_events',
        default=None,
        blank=True,
        verbose_name="bookmarks"
    )
    tags = models.ManyToManyField(
        'Tag',
        related_name='tag_events',
        default=None,
        blank=True,
        verbose_name="tags"
    )

    pub_date = models.DateTimeField(
        'Event publish date',
        auto_now_add=True,
    )

    start_date = models.DateTimeField(
        'Event start date',
        auto_now_add=True,
    )
    end_date = models.DateTimeField(
        'Event end date',
        auto_now_add=True,
    )

    address = models.CharField(
        'Address',
        max_length=255,
        blank=True,
    )
    longitude = models.FloatField(
        'Longitude',
        null=True,
        blank=True,
    )
    latitude = models.FloatField(
        'Latitude',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Event'
        verbose_name_plural = 'Events'
        ordering = ['-pub_date']

    @property
    def num_likes(self):
        return self.liked.count()
    
    @property
    def num_bookmarks(self):
        return self.bookmarked.count()


LIKE_CHOICES = (
    ('like', 'like'),
    ('dislike', 'dislike'),
)


class Like(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
    )
    value = models.CharField(
        choices=LIKE_CHOICES,
        default='like',
        max_length=10,
    )


class Bookmark(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
    )


class Tag(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True,
    )
    events = models.ManyToManyField(
        Event,
        related_name='tag',
        blank=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

jasa/events/views.py
from typing import Optional

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required 
from django.contrib.auth import get_user_model

from core.decorators.ajax_decorator import ajax_login_required
from .constants import NUM_LOAD_EVENTS
from .models import Event, Tag


User = get_user_model()


def paginator_events(request, event_list, num_of_events_per_page):
    """Paginator events."""
    page_number = request.GET.get('page')
    paginator = Paginator(event_list, num_of_events_per_page)

    return paginator.get_page(page_number)


def index(request):
    """Render NUM_LOAD_EVENTS most recent events."""
    template_name = 'events/index.html'
    event_list = Event.objects.all()
    page_obj = paginator_events(request, event_list, NUM_LOAD_EVENTS)

    context = {
        'page_obj': page_obj,
        'show_full': False,
    }
    
    return render(request, template_name, context)


def event_details(request, event_id: int):
    """Render event details."""
    template_name = 'events/event_details.html'
    event = Event.objects.get(id=event_id)

    context = {
        'event': event,
        'show_full': True,
    }

    return render(request, template_name, context)


def profile(request, username: str):
    """Render profile page."""
    template_name = 'events/profile.html'

    username = username or request.user.username
    if not username:
        return redirect('users:login')

    user = get_object_or_404(User, username=username)
    event_list = user.events.all()
    page_obj = paginator_events(request, event_list, NUM_LOAD_EVENTS)

    context = {
        'profile': user,
        'page_obj': page_obj,
    }

    return render(request, template_name, context)


def search(request):
    """Render search page."""
    template_name = 'events/search.html'

    tags = Tag.objects.all()

    context = {
        'tags': tags,
    }

    return render(request, template_name, context)


@ajax_login_required
def like_event(request):
    user = request.user

    try:
        if request.method == 'POST':
            event_id = request.POST.get('event-id')
            event = Event.objects.get(id=event_id)
            
            if user in event.liked.all():
                event.liked.remove(user)
            else:
                event.liked.add(user)

            return JsonResponse({
                'status': 'OK',
                'count': event.num_likes,
                'event-id': event_id,
            })
    except Exception as e:
        print(e)
        return JsonResponse({
            'status': 'ERROR',
        })


@ajax_login_required
def bookmark_event(request):
    user = request.user

    try:
        if request.method == 'POST':
            event_id = request.POST.get('event-id')
            event = Event.objects.get(id=event_id)
            
            if user in event.bookmarked.all():
                event.bookmarked.remove(user)
            else:
                event.bookmarked.add(user)

            return JsonResponse({
                'status': 'OK',
                'count': event.num_bookmarks,
                'event-id': event_id,
            })
    except Exception as e:
        print(e)
        return JsonResponse({
            'status': 'ERROR',
        })

jasa/templates/events/event_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{event.title}}{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/events/index.css' %}">
  <link rel="stylesheet" href="{% static 'css/events/like_button.css' %}">
{% endblock %}

{% block header_left %}
  <a class="tg-link-color" href="{% url 'events:index' %}">Back</a>
{% endblock %}
{% block header_title %}{{event.title}}{% endblock %}

{% block content %}
  {% include 'events/includes/event.html' %}  
{% endblock %}


{% block js %}
  <script>
    var like_url = '{% url "events:like_event" %}';
    var bookmark_url = '{% url "events:bookmark_event" %}';
  </script>

  <script src="{% static 'js/post.js' %}"></script>
  <script src="{% static 'js/events/index.js' %}"></script>
{% endblock %}

jasa/templates/events/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/events/like_button.css' %}">
{% endblock %}


{% block title %}Мероприятие{% endblock title %}

{% block header_title %}Текущее мероприятие{% endblock %}

{% block content %}
  <div class="event-list">
    {% for event in page_obj %}
      {% include 'events/includes/event.html' %}
    {% endfor %}
    {% if page_obj.has_next %}
      <p class="pagination">
        <a class="next-page" href="?page={{ page_obj.next_page_number }}">Больше...</a>
      </p>
    {% else %}
      <p class="text-center tg-hint-color text-muted">
        Больше нет никаких мероприятие
      </p>
    {% endif %}
  </div>
{% endblock content %}

{% block js %}
  <script>
    var like_url = '{% url "events:like_event" %}';
    var bookmark_url = '{% url "events:bookmark_event" %}';
  </script>

  <script src="{% static 'js/post.js' %}"></script>
  <script src="{% static 'js/events/index.js' %}"></script>


  {% comment %} 
    jScroll plug-in CDN
    https://github.com/pythonsansar/infinite-scrolling-django/blob/master/books/templates/books/book-list.html
  {% endcomment %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
  <script>
    jQuery(function ($) {
      var $list = $('.event-list');
      $list.jscroll({
        loadingHtml: `{% include "includes/loading.html" %}`,
        pagingSelector: '.pagination',
        nextSelector: 'a.next-page:last',
        contentSelector: '.card,.pagination'
      });
    });
  </script>
{% endblock %}

jasa/templates/events/profile.html
{% extends 'base.html' %}


{% block title %}{{profile.username}}'s profile{% endblock title %}

{% block header_title %}{{profile.username}}'s profile{% endblock %}

jasa/templates/events/search.html
{% extends 'base.html' %}

{% block title %}Поиск{% endblock %}
{% block header_title %}Поиск{% endblock %}

{% block content %}
  {% for tag in tags %}
    <a href="{% url 'events:index' %}">{{ tag }}</a>
    <hr>
  {% endfor %}
{% endblock %}